######################################################################
# Automatically generated by qmake (3.0) ?? 10? 26 09:32:02 2018
######################################################################

TEMPLATE = app
TARGET = qt_test
INCLUDEPATH += .

# Input
SOURCES += hello_world.cpp
